config/routes.rb
Rails.application.routes.draw do

  root 'tickets#new'
  
  resources :tickets do
    resources :answers
  end
  
  devise_for :users
  resources :users
  resources :statuses
  resources :departments
  

end

app/models/answer.rb
class Answer < ActiveRecord::Base

  belongs_to :user
  belongs_to :ticket

  validates :answer_text, presence: true

end

app/models/department.rb
class Department < ActiveRecord::Base

  belongs_to :ticket

  validates :department_type, presence: true

end

app/models/status.rb
class Status < ActiveRecord::Base
  
  belongs_to :ticket

  validates :status_type, presence: true
  
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  
  has_many :statuses
  has_many :answers
  
  validates :name, presence: true
  validates :email, presence: true
  validates :text, presence: true

  after_create :reindex!
  after_update :reindex!

  scope :filter_status, -> (status) {where status: status}
 
  searchable do
    text :key
    text :name
    text :subject 
    text :staff_name
  end
   
  protected
  
  def self.counter(s)
    where(status:s).to_a.size
  end
 
  def reindex!
  	Sunspot.index!(self)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	
  has_many :answers

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def index
	@answers = Answer.all
  end

  def new
	@answer = Answer.new
  end

  def create
    answer = Answer.new(answer_params)
    @ticket = Ticket.find(params[:ticket_id])
    answer.user_id = current_user.id if user_signed_in?
    	if answer.save
   		  UserMailer.answer_status(answer).deliver
		    flash[:success] = "Answer deliver."
		  else
		    flash.now[:error] = "You have errors!"
		  end
    redirect_to ticket_path(Ticket.find(answer.ticket_id).key)
  end
  
  def destroy
    @answer.destroy
  end
	
  private

  def answer_params
  	params.require(:answer).permit(:answer_text).merge(ticket_id: params[:ticket_id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  	tickets_path
  end

end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController

  before_action :set_department, only: [:show, :edit, :update, :destroy]

  def index
  	@departments = Department.all
    @department = Department.new
    @n = 1
  end

  def new
  	@department = Department.new
  end

  def create
  	@department = Department.new(department_params)
    if @department.save
      flash[:success] = "Department created."
      redirect_to departments_url
    else
      flash[:error] = "You have errors!"
      redirect_to departments_url
    end
  end

  def destroy
    @department.destroy
    flash[:success] = "Department deleted."
    redirect_to departments_url
  end

  private

  def set_department
    @department = Department.find_by_id(params[:id])
  end

  def department_params
  	params.require(:department).permit(:department_type)
  end

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController

  before_action :set_status, only: [:show, :edit, :update, :destroy]

  def index
  	@statuses = Status.all
    @status = Status.new
    @n = 1
  end

  def new
    @status = Status.new
  end

  def create
  	@status = Status.new(status_params)
    if @status.save
      flash[:success] = "Status created."
      redirect_to statuses_url
    else
      flash[:error] = "You have errors in your form!"
      redirect_to statuses_url
    end
  end

  def destroy
    @status.destroy
    flash[:success] = "Status deleted."
    redirect_to statuses_url
  end

  private

  def set_status
    @status = Status.find_by_id(params[:id])
  end

  def status_params
  	params.require(:status).permit(:status_type)
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

	before_filter :authenticate_user!, except: [:new, :create, :show]
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
		
	def index
    @tickets = Ticket.all
    @tickets = @tickets.filter_status(filter_params[:filter_status]) if filter_params[:filter_status].present?
		@tickets = Ticket.search{fulltext params[:search]}.results if params[:search].present?
    @new_count = Ticket.counter("Waiting for Staff Response")
    @open_count = Ticket.counter("Waiting for Customer")
    @on_hold_count = Ticket.counter("On Hold")
    @cancelled_count = Ticket.counter("Cancelled")
    @closed_count = Ticket.counter("Completed")
    @all_count = Ticket.all.size
  end

	def new
		@ticket = Ticket.new
	end

	def create
    @ticket = Ticket.new(ticket_params)
    if user_signed_in?
      redirect_to tickets_url
      flash[:error] = "Ticket create only customer"
      return
    end
    key = "#{('A'..'Z').to_a.sample(3).join}-#{rand(100000..999999)}"
    @ticket.key = key
    @ticket.status = Status.find_by(status_type: 'Waiting for Staff Response').status_type
		if @ticket.save
      UserMailer.create_ticket(@ticket).deliver
      flash[:success] = "Ticket created! Check your mail."
			redirect_to(action: "show", id: @ticket.key)
   	else
   		flash[:error] = "You have errors in your form!"
   		render "new"
    end
  end
		
	def destroy
    @ticket.destroy
    redirect_to tickets_url
    flash[:success] = 'Ticket was successfully destroyed.'
  end

	def update
    if signed_in?
      @ticket.update_attributes(ticket_params)
      UserMailer.update_ticket(@ticket).deliver
      flash[:success] = 'Email deliver'
      redirect_to tickets_url
    else
      @ticket = Ticket.find_by(key: params[:id])
      @ticket.update_attributes(params[:ticket])
      redirect_to(action: "show", id: @ticket.key)
    end
  end

	def show
    @ticket = Ticket.find_by(key: params[:id])
  end

	private

  def set_ticket
    @ticket = Ticket.find_by_id(params[:id])
  end

	def ticket_params
    params.require(:ticket).permit(:key, :name, :email, :department, :subject, :text, :status, :staff_name)
  end

  def filter_params
    params.permit(:filter_status)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
    @user = User.new
    @n = 1
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
    if @user.save
      flash[:success] = "User created."
      redirect_to users_url
    else
      flash[:error] = "You have errors!"
      redirect_to users_url
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private

  def set_user
    @user = User.find_by_id(params[:id])
  end

  def user_params
  	params.require(:user).permit(:user_name, :email, :password)
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/departments/index.html.haml
%h1(align="center") Departments
%br
.row
  .col-md-2
  .col-md-4
    %center
      %h2 New department
      = simple_form_for(@department) do |d|
        .form-inputs
          = d.input :department_type, placeholder: "Enter department"
        .form-actions
          = d.button :submit, class: "btn btn-primary"
  .col-md-2
    %br
    %table.table.table-hover.table-bordered
      %thead
        %tr
          %th №
          %th Department
          %th
        %tbody
          - @departments.each do |d|
            %tr
              %td= @n
              %td= d.department_type
              %td= link_to 'Destroy', d, :method => :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs"
            - @n += 1
  .col-md-4

app/views/layouts/_footer.html.haml
%footer
  .navbar-fixed-bottom(align="right") Support Issue Tracking 2016

app/views/layouts/_header.html.haml
.navbar
  = render partial: "shared/frontend_notifier"
  .raw
    .col-md-7.logo
      - if signed_in?
        = link_to "Support Issue Tracking", root_path
      - else
        = link_to "Support Issue Tracking", root_path, class: "unsign"
    .col-md-1.nav-links
      = link_to "Tickets", tickets_path if signed_in?
    .col-md-1.nav-links
      = link_to "Statuses", statuses_path if signed_in?
    .col-md-1.nav-links
      = link_to "Departments", departments_path if signed_in?
    .col-md-2
      %ul
        - if signed_in?
          %li
            = link_to "#{current_user.user_name}", users_path
          %li
            = link_to "Sign out", destroy_user_session_path, :method => :delete
        - else
          %li
            = link_to "Sign in", new_user_session_path, class: "unsign-link"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SupportIssueTracking
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    = yield
    = render "layouts/footer"

app/views/statuses/index.html.haml
%h1(align="center") Statuses
%br
.row
  .col-md-2
  .col-md-4
    %center
      %h2 New status
      = simple_form_for(@status) do |s|
        .form-inputs
          = s.input :status_type, placeholder: "Enter status"
        .form-actions
          = s.button :submit, class: "btn btn-primary"
  .col-md-2
    %br
    %table.table.table-hover.table-bordered
      %thead
        %tr
          %th №
          %th Type
          %th
        %tbody
          - @statuses.each do |s|
            %tr
              %td= @n
              %td= s.status_type
              %td= link_to 'Destroy', s, :method => :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs"
            - @n += 1
  .col-md-4

app/views/tickets/index.html.haml
.container-fluid
  .row
    .col-md-1
    .col-md-10    
      %h1(align="center") Tickets History
      .row
        .col-md-4
          = form_tag request.original_url, :method => 'get', :class => 'form-inline' do
            %container
              = text_field_tag :search, params[:search], :placeholder => "Search", :class => 'form-control'
              = submit_tag "Go", :name => nil, :class => 'btn btn-default'
        .col-md-8
          = link_to "All Tickets:#{@all_count}", tickets_path, :class => "btn btn-info"
          = link_to "New unussigned:#{@new_count}", {:filter_status => "Waiting for Staff Response"}, :class => "btn btn-success"
          = link_to "Open:#{@open_count}", {:filter_status => "Waiting for Customer"}, :class => "btn btn-success"
          = link_to "On Hold:#{@on_hold_count}", {:filter_status => "On Hold"}, :class => "btn btn-success"
          = link_to "Cancelled:#{@cancelled_count}", {:filter_status => "Cancelled"}, :class => "btn btn-success"
          = link_to "Closed:#{@closed_count}", {:filter_status => "Completed"}, :class => "btn btn-success"
      %br
      %table.table.table-condensed.table-hover.table
        %thead
          %tr.text-info.danger
            %th Name
            %th E-mail
            %th Department
            %th Subject
            %th Reference
            %th Status
            %th Responsible
            %th Change status
            %th
            %th
        %tbody
          - @tickets.each do |t|
            %tr
              %td= t.name
              %td= t.email
              %td= t.department
              %td= t.subject
              %td= t.key
              %td.text-success
                %b= t.status
              %td= t.staff_name
              %td
                = simple_form_for(t) do |f|
                  = collection_select(:ticket, :status, Status.all, :status_type, :status_type)
                  %p.hidden= select(:ticket, :staff_name, [current_user.user_name])
                  = f.submit 'Confirm', class: "btn btn-warning btn-xs"
              %td= link_to "Show", "/tickets/#{t.key}", class: "btn btn-info btn-xs"
              %td= link_to 'Destroy', t, :method => :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs"
    .col-md-1

app/views/tickets/new.html.haml
.container-fluid
  .row
    .col-md-3
    .col-md-6
      .panel
        %h1(align="center") New ticket
        = simple_form_for(@ticket) do |f|
          .panel-body.form-inputs(align="center")
            = f.input :name, placeholder: "Write you name"
            = f.input :email, placeholder: "Write you email"
            = f.input :subject, placeholder: "Enter subject"
            %center 
              %b Department:
              = collection_select(:ticket, :department, Department.all, :department_type, :department_type)
            = f.text_area :text, placeholder: "Enter issue"
          .panel-footer.form-actions(align="center")
            = f.button :submit, class: "btn btn-primary"

app/views/tickets/show.html.haml
.container-fluid
  .row
    .col-md-1
    .col-md-1
      - if signed_in?
        =link_to "Back", tickets_url, class: "btn btn-link back"
      - else
        =link_to "Back", root_path, class: "btn btn-link back"
    .col-md-1
    .col-md-6
      .panel.panel-warning
        .panel-heading
          .row
            .col-md-7
              %h2
                %strong Ticket from #{@ticket.name}
                %br 
                - if @ticket.staff_name
                  %span.text-muted
                    responsible officer name: #{@ticket.staff_name}
            .col-md-2
              %h3 Status:
            .col-md-3
              %h3.text-success #{@ticket.status}
          %ul.list-group
            %li.list-group-item
              %b Created: 
              %big #{@ticket.created_at.localtime.strftime("%H:%M %d-%b %Y")}
            %li.list-group-item
              %b Subject:
              %big #{@ticket.subject}
            %li.list-group-item 
              %b Department:
              %big #{@ticket.department}
            %li.list-group-item
              %b Text:
              %big #{@ticket.text}
        .panel-body
          -if @ticket.answers.length > 0
            %h4 Answers:
          %ul.list-group
            - @ticket.answers.each do |f|
              %li.list-group-item
                - if f.user
                  %b.text-primary #{f.user.user_name}
                - else
                  %b.text-danger Your message
                %small.text-muted= f.created_at.localtime.strftime("%H:%M %d-%b %Y")
                %big
                  %br= f.answer_text
        .panel-footer
          = simple_form_for [@ticket, @ticket.answers.create] do |f|
            .form-inputs
              = f.text_area :answer_text, class: "form-control"
            .form-actions
              = f.submit "Send Answer", class: "btn btn-md btn-info"

app/views/users/index.html.haml
%h1(align="center") Users
%br
.row
  .col-md-3
  .col-md-6
    %br
    %table.table.table-hover.table-bordered
      %thead
        %tr
          %th №
          %th Name
          %th Email
          %th Last visit
          %th IP
        %tbody
          - @users.each do |u|
            %tr
              %td= @n
              %td= u.user_name
              %td= u.email
              %td= u.last_sign_in_at.localtime.strftime("%H:%M %d-%b %Y")
              %td= u.last_sign_in_ip
            - @n += 1
  .col-md-3